spring:
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
    # Specify which components to load for better control over bean loading order
    banner-mode: off
  datasource:
    url: jdbc:postgresql://db:5432/product_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    enabled: true
    bootstrap-servers: kafka:9092
    topics:
      product-created: product-created
      product-updated: product-updated
      product-deleted: product-deleted
      inventory-updated: inventory-updated
      product-events: product-events
      product-analytics: product-analytics
    producer:
      client-id: product-service-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.ecommerce.product.event,com.ecommerce.product.kafka.event
        spring.json.type.mapping: product-event:com.ecommerce.product.event.ProductEvent,enhanced-event:com.ecommerce.product.kafka.event.EnhancedProductEvent
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      linger-ms: 10
      compression-type: snappy
    consumer:
      group-id: product-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.ecommerce.product.kafka.event,com.ecommerce.product.event

# Kafka topics configuration to match KafkaConfig class expectations
kafka:
  topics:
    product-created: product-created
    product-updated: product-updated
    product-deleted: product-deleted
    inventory-updated: inventory-updated
    product-events: product-events
    product-analytics: product-analytics

server:
  port: 8080

logging:
  level:
    com.ecommerce.product: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

# Application feature configuration for enhanced streaming capabilities
application:
  features:
    simulator:
      enabled: true
      rate: 5000
      batch-size: 3
    analytics:
      realTimeEnabled: true
      bufferSize: 100
      flushIntervalMs: 5000

# Enable Micrometer metrics for Kafka monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        kafka.producer.message.latency: true
