apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: ecommerce
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181
    name: client
  - port: 2888
    targetPort: 2888
    name: server
  - port: 3888
    targetPort: 3888
    name: leader-election
  type: ClusterIP
