apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: ecommerce
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
    name: internal
  - port: 29092
    targetPort: 29092
    name: external
  type: ClusterIP
