apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: ecommerce
  labels:
    app: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
