apiVersion: v1
kind: Service
metadata:
  name: product-service-service
  namespace: ecommerce
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
