apiVersion: v1
kind: Pod
metadata:
  name: pg-test
  namespace: ecommerce
spec:
  containers:
  - name: postgres
    image: postgres:14
    command: ["sleep", "3600"]
    env:
    - name: PGPASSWORD
      value: "YOUR_DB_PASSWORD"
