apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ecommerce
data:
  POSTGRES_PASSWORD: "YOUR_DB_PASSWORD"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "product_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-fixed
  namespace: ecommerce
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "YOUR_DB_PASSWORD"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "product_db"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ecommerce
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
