apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-nopvc
  namespace: ecommerce
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-service-secrets
              key: SPRING_DATASOURCE_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: product-service-secrets
              key: SPRING_DATASOURCE_USERNAME
        - name: POSTGRES_DB
          value: product_db
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
