apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-test
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-test
  template:
    metadata:
      labels:
        app: postgres-test
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "simple123"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "testdb"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-test
  namespace: ecommerce
spec:
  selector:
    app: postgres-test
  ports:
  - port: 5432
    targetPort: 5432
