apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-fixed
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service-fixed
  template:
    metadata:
      labels:
        app: product-service-fixed
    spec:
      containers:
      - name: product-service
        image: YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/ecommerce-product-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "postgres"
        - name: SPRING_CONFIG_LOCATION
          value: "classpath:/,/config/"
        - name: SPRING_KAFKA_ENABLED
          value: "false"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/product_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "YOUR_DB_PASSWORD"
        - name: SPRING_FLYWAY_ENABLED
          value: "true"
        - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
          value: "true"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: config-volume
        configMap:
          name: product-service-fixed-config
