apiVersion: v1
kind: Service
metadata:
  name: product-service-fixed
  namespace: ecommerce
spec:
  selector:
    app: product-service-fixed
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
