apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-fixed-config
  namespace: ecommerce
data:
  application.yml: |
    spring:
      application:
        name: product-service
      profiles:
        active: postgres
      datasource:
        url: jdbc:postgresql://postgres-service:5432/product_db
        username: postgres
        password: YOUR_DB_PASSWORD
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: 5
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
      jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
      flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration
      kafka:
        enabled: false
    
    server:
      port: 8081
      
    logging:
      level:
        com.ecommerce.product: DEBUG
        org.springframework: INFO
        org.springframework.jdbc: DEBUG
        org.hibernate: INFO
        com.zaxxer.hikari: DEBUG
