apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: ecommerce
data:
  # Enable bean overriding for Kafka config
  SPRING_MAIN_ALLOW-BEAN-DEFINITION-OVERRIDING: "true"
  
  # JPA Configuration
  SPRING_JPA_HIBERNATE_DDL-AUTO: "update"
  SPRING_JPA_GENERATE-DDL: "true"
  SPRING_JPA_DATABASE-PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_SHOW-SQL: "true"
  
  # Disable Flyway to prevent migration conflicts
  SPRING_FLYWAY_ENABLED: "false"
  
  # Hibernate pool configuration
  SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_PROVIDER_DISABLES-AUTOCOMMIT: "true"
  
  # HikariCP specific configuration
  SPRING_DATASOURCE_HIKARI_MINIMUMIDE: "2"
  SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: "10"
  SPRING_DATASOURCE_HIKARI_IDLETIMEOUT: "30000"
  SPRING_DATASOURCE_HIKARI_POOLNAME: "SpringBootHikariCP"
  SPRING_DATASOURCE_HIKARI_MAXLIFETIME: "2000000"
  SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT: "30000"
  
  # Kafka Configuration
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "kafka-service:9092"
  KAFKA_CREATE_TOPIC_ENABLED: "false"
